### ISSUE TITLE
Create Approach Units Profiles/Screens/Symbology

### ISSUE THREAD

**Issue by luke11brown** [luke11brown/UK-TopSky-Controller-Pack#20]
Gather Data for systems in use

Park Air (Blue/Grey)
- Manchester
- Edinburgh
- Glasgow
- Aberdeen
- Liverpool
- Bristol
- Cardiff

Ancient 80's Style
- East Midlands

Unknown
- Farnborough
- Norwich
- Inverness
- Birmingham
- Southend
- Newquay
- Bournemouth
- Southampton

**Comment by danielbutton** [comment]
I have symbology settings for Cardiff and Newquay if you'd like to have a look?

**Comment by luke11brown** [comment]
Yeah feel free to either drop here told submit a PR
