### ISSUE TITLE
Create file with MSA data for UK

### ISSUE THREAD

**Issue by MikePike-collab** [luke11brown/UK-TopSky-Controller-Pack#28]
The file TopSkyMSAW.txt to be created to contain the data displayed geographically in the UKAIP at ENR 6-81 (UK Area Minimum Altitudes).

**Comment by MikePike-collab** [comment]
Requires TopSky ALRT Message tag item added to line 0 of tags to see the MSAW alerts

**Comment by MikePike-collab** [comment]
[TopSkyMSAW.txt](https://github.com/luke11brown/UK-TopSky-Controller-Pack/files/5371498/TopSkyMSAW.txt)

Updates from AIRAC 2020/11 added.
corrected 2 missing areas
Added experimental MSA sectors for Aberdeen/Dyce. MSAW triggers near airports are going to be more complicated than I thought if we are to avoid false alarms for arriving and departing aircraft.

**Comment by luke11brown** [comment]
Wiki Updated!
