### ISSUE TITLE
Voice communication Setup dialog in ES doesn't display any data

### ISSUE THREAD

**Issue by MikePike-collab** [luke11brown/UK-TopSky-Controller-Pack#33]
Looks like the settings file voice.txt is missing the last two fields on each line. Means you can't set primary frequency when connecting or connect an atis.
![image](https://user-images.githubusercontent.com/70595770/92969483-fa3e6c00-f474-11ea-8c69-f8466cf622a9.png)

**Comment by luke11brown** [comment]
At first glance it looks like you’re using an older version of ES. Have you tried with the latest beta release (r25)

The voice comma dialog has changed a fair bit, voice servers are no longer needed to be defined

**Comment by MikePike-collab** [comment]
Yes that's right. Upgraded to r25 and the problem is fixed. This issue can be resolved by a statement somewhere that the controller pack requires ES beta version r25 and is not compatible with r23 and before.
