### ISSUE TITLE
CPDLC mistakes

### ISSUE THREAD

**Issue by hsugden** [luke11brown/UK-TopSky-Controller-Pack#51]
https://github.com/luke11brown/UK-TopSky-Controller-Pack/blob/ae947ee25cc264502e01ffdb9d30166e9c26cd87/UK-TopSky/Data/Plugin/TopSky/TopSkyCPDLC.txt#L4

Spelling mistakes to fix

Line 5 - Monitor
Line 6 - Unavailable
Line 7 - Service

**Comment by luke11brown** [comment]
fixed in 5f37d8c76e053803bcd82a608f234393b27523d7
