### ISSUE TITLE
MSAW system has false positives on final approach

### ISSUE THREAD

**Issue by MikePike-collab** [luke11brown/UK-TopSky-Controller-Pack#52]

**Comment by MikePike-collab** [comment]
The circle at airfield elevation covers terrain for a radius of 2 miles from the airport but approaching aircraft will be below any other MSA before reaching 2 miles - Eg at EGKK...
![image](https://user-images.githubusercontent.com/70595770/97752900-cda9e680-1aec-11eb-9221-11dbf26f853a.png)
The circle also creates false negatives should aircraft get within 2 miles at low level but not on the approach/climbout track.

**Comment by MikePike-collab** [comment]
![image](https://user-images.githubusercontent.com/70595770/97802035-aeb86b00-1c38-11eb-868f-b316fc3147d6.png)
Proposal is to create cones along the approach path from FAF  where descent is terrain safe using a formula based on runway true bearing, distance to the FAF and any step down fixes between. (screen grab shows the result for EGKK)

**Comment by luke11brown** [comment]
Fixed in 6eef02090d7a483e7315f3f3039bc95b9d77c121

Except EGNJ
