### ISSUE TITLE
SSRcodes

### ISSUE THREAD

**Issue by morettio** [luke11brown/UK-TopSky-Controller-Pack#53]
Hi!

I see that the SSR codes that VatUK is using are the same as in Sweeden. This is not a good thing for us in Norway/Denmark that also use topsky. The SSR codes are taken out of the system Eurocontrol uses, Se link.

https://www.eurocontrol.int/publication/secondary-surveillance-radar-code-allocation-list-icao-eur-region-cal

If any questions about the setup of this file or if you want to see The Norwegian SSR file, please let me know :)

**Comment by luke11brown** [comment]
Whilst the file is there, it essentially, isn't used as our squawks are auto generated by the UKCP.
Nonetheless, I will remove the file and see what effect it has.

**Comment by luke11brown** [comment]
Fixed in 301748aab090a3028a9774e1f13ac8647e92cb0f
